"""Base exceptions."""

from abc import ABC


class ClientError(ABC, Exception):
    """The base exception for client errors.

    This exception should be thrown when an error originating from client input occurs.
    These types of exception should almost always be recoverable. This base exception is
    marked as abstract because a more descriptive exception should always be thrown.
    """

    pass


class ModelLookupError(ClientError):
    """An exception which occurs during model lookup.

    This exception occurs when fetching data from the model database or other such
    situations when attempting to locate a model by its primary key.

    """

    pass


class GameStateError(ClientError):
    """An exception generated by input which would put the game in a impossible state.

    An example of impossible state is attempting to start multiple Jams at the same time
    or attempting to end a period when one isn't already running.

    """

    pass


class GameRulesError(ClientError):
    """An exception stemming from a roller derby Ruleset.

    This describes game states which are possible, but are either not allowed or not
    described by the ruleset of this Bout.

    An example would be declaring two lead Jammers at the same time in the WFTDA 2025
    ruleset. In WFTDA 2025, only one Jammer may be declared the lead per Jam.

    """

    pass


class UserStateError(ClientError):
    """An error occurred while managing a user's state.

    These types of exceptions occur in the user service. An example of such an error is
    when a user tries to undo their last command but there are no commands on the user's
    command history.

    """

    pass
