[project]
dependencies = [
  "aiosqlite~=0.21.0",
  "fastapi~=0.115.12",
  "nanoid~=2.0.0",
  "pyinstaller~=6.12.0",
  "requests~=2.31.0",
  "ruff~=0.12.2",
  "SQLAlchemy~=2.0.41",
  "uvicorn~=0.34.2",
  "websockets~=15.0.1",
]
name = "nso-bridge"
requires-python = ">=3.13"
version = "0.1.0"

[tool.pyrefly]
project-includes = [
  "**/*.py*",
  "**/*.ipynb",
]
search_path = [
  "backend",
]

[tool.ruff]
indent-width = 4
line-length = 88

[tool.ruff.format]
indent-style = "space"
quote-style = "single"

[tool.ruff.lint]
extend-select = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "I",
  "FAST",
  "PL",
  "EXE",
  "TC", # Put imports in TYPE_CHECKING blocks when possible
]
ignore = [
  'D', # TODO: add docs
]

[tool.ruff.lint.extend-per-file-ignores]
"dependencies.py" = [
  "PLR0913", # Dependency methods may have more arguments than typical
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = false

[tool.setuptools.packages.find]
include = [
  "backend",
]
