[project]
dependencies = [
  "aiosqlite>=0.22.1",
  "argparse>=1.4.0",
  "colorlog>=6.10.1",
  "fastapi[standard]>=0.115.14",
  "pytest>=9.0.2",
  "requests>=2.32.5",
  "sqlalchemy>=2.0.45",
  "uvicorn>=0.34.3",
  "websockets>=15.0.1",
]
name = "nso-bridge"
requires-python = ">=3.13"
dynamic = ["version"]

[tool.pyrefly]
project-includes = ["**/*.py*", "**/*.ipynb"]
search_path = ["backend"]

[tool.ruff]
indent-width = 4
line-length = 88

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 88
indent-style = "space"
quote-style = "single"

[tool.ruff.lint]
extend-select = [
  "A",    # flake8 builtins
  "B",    # flake8 bugbear
  "C",    # McCabe complexity
  "D",    # Documentation
  "E",    # pycodestyle errors
  "F",    # Pyflakes
  "I",    # Import sorting
  "FAST", # FastAPI
  "PL",   # Pylint
  "EXE",  # flake8 executable
  "TC",   # flake8 type checking
  "N",    # pep8 naming conventions
  "S",    # flake8 bandit
]
ignore = [
  "D203", # No blank lines allowed before class docstring
  "D213", # Multi-line docstring summary should start at the first line
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = false

[tool.setuptools.packages.find]
include = ["backend"]

[dependency-groups]
dev = ["ruff>=0.14.10"]
