"""Constants used for the Bouts sub-module."""

RANDOM_TEAM_NAMES: list[tuple[str, str]] = [
    ('Home', 'Away'),
    ('Sun', 'Moon'),
    ('Salt', 'Pepper'),
    ('Black', 'White'),
    ('Ocean', 'Desert'),
    ('Fire', 'Ice'),
    ('Mountain', 'Valley'),
    ('Day', 'Night'),
    ('Storm', 'Calm'),
    ('Light', 'Dark'),
    ('Gold', 'Silver'),
    ('Chaos', 'Order'),
    ('Introverts', 'Extroverts'),
    ('Hot', 'Cold'),
    ('Loud', 'Quiet'),
    ('Cats', 'Dogs'),
    ('Coffee', 'Tea'),
    ('Sweet', 'Sour'),
    ('Books', 'Movies'),
    ('Push', 'Pull'),
    ('Humans', 'Machines'),
    ('Heroes', 'Villains'),
    ('Angels', 'Demons'),
    ('Necromancers', 'Paladins'),
    ('Wizards', 'Warlocks'),
    ('Zombies', 'Ninjas'),
    ('Sharks', 'Jets'),
    ('North', 'South'),
    ('East', 'West'),
    ('Spring', 'Autumn'),
    ('Summer', 'Winter'),
    ('Fireflies', 'Lightning Bugs'),
    ('Brains', 'Brawn'),
    ('Alpha', 'Omega'),
    ('Soup', 'Salad'),
    ('Dinosaurs', 'Asteroids'),
    ('Duct Tape', 'WD-40'),
    ('Cats', 'Laser Pointers'),
    ('Bananas', 'Peels'),
]
"""A list of random team names that are used to create Bouts when no team names are
specified."""
