# Test the Application Backend.
#
# This workflow runs when a a commit is pushed. It sets up the programming environment
# and runs test scripts for the backend.
name: Test Backend
on: push

jobs:
  setup-environment:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    # Setup the Node.js frontend
    - name: Install Node.js
      uses: actions/setup-node@v4
    - name: Install Node.js dependencies
      run: npm install
    - name: Build frontend
      run: npm run build

    # Setup the Python backend
    - name: Install Astral uv
      uses: astral-sh/setup-uv@v7
      with:
        activate-environment: "true"
    - name: Setup python virtual environment
      run: uv venv
    - name: Install python dependencies
      run: uv sync

  test:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Run pytest
        run: pytest
