name: Deploy
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Setup the Node.js frontend
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install Node.js dependencies
        run: npm install
      - name: Build frontend
        run: npm run build

      # Setup the Python backend
      - name: Install Astral uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: "true"
      - name: Setup Python virtual environment
        run: uv venv
      - name: Install Python dependencies
        run: uv sync

      # TODO: Ensure that the app version matches the Tag

      # Test the backend
      # - name: Run Pytest
      #   run: pytest

      # Bundle the application
      - name: Bundle application
        run: pyinstaller ./onedir.spec -y
      - name: Remove unused folder on MacOS
        if: runner.os == 'macOS'
        run: rm -rf "./dist/NSO Bridge"

      # Get artifacts
      - name: Upload application artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nsobridge-${{ runner.os }}
          path: "./dist"

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: List artifacts
        run: ls -la artifacts

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref }}
          draft: true
          generate_release_notes: true
          files: |
            ./artifacts/*
          token: ${{ secrets.GITHUB_TOKEN }}
