name: Deploy
on: [push]
jobs:
  Test-Backend:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    # Setup the Node.js frontend
    - name: Install Node.js
      uses: actions/setup-node@v4
    - name: Install Node dependencies
      run: npm install
    - name: Build frontend
      run: npm run build

    # Setup the Python backend
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        activate-environment: "true"
        python-version: 3.13
    - name: Setup the virtual environment
      run: uv venv | uv sync

    # Run Pytest
    - name: Run Pytest
      run: pytest
  Bundle-Application:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Setup the Node.js frontend
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install Node dependencies
        run: npm install
      - name: Build frontend
        run: npm run build

      # Setup the Python backend
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: "true"
      - name: Setup the virtual environment
        run: uv venv | uv sync
      - name: Compile the application
        run: pyinstaller ./onedir.spec -y


      - name: Upload the folder as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: nsobridge-${{ runner.os }}
          path: "./dist/NSO Bridge"
          retention-days: 5 # Optional: how long to keep the artifact
