# Lint, test, and build the application.
#
# This workflow runs when a a commit is pushed. It sets up the programming environment
# and runs linting, testing, and build scripts. 
name: Lint Frontend
on:
  workflow_call:
    secrets:
        personal_access_token:
          required: false
jobs:
  lint_frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: someweisguy/NSOBridge/.github/workflows/setup-frontend.yaml@dev
      - name: Run linter scripts
        run: npm run lint
 
  # test_frontend:
  #   name: Test Frontend
  #   runs-on: ubuntu-latest
  #   needs: setup_environment
  #   if: false  # TODO: add frontend testing
  #   steps:
  #     - name: Pass
  #       run: ls
  # build_frontend:
  #   name: Build Frontend
  #   runs-on: ubuntu-latest
  #   needs: setup_environment
  #   steps:
  #     - name: Run build scripts
  #       run: npm run lint

  # lint_backend:
  #   name: Lint Backend
  #   runs-on: ubuntu-latest
  #   needs: setup_environment
  #   steps:
  #     - name: Ruff check
  #       run: ruff check . --ignore EXE001
  #     - name: Ty check
  #       run: ty check
  # test_backend:
  #   name: Test Backend
  #   runs-on: ubuntu-latest
  #   needs: [setup_environment, build_frontend]
  #   steps:
  #     - name: Run pytest
  #       run: pytest
  # build_backend:
  #   name: Build Backend
  #   runs-on: ubuntu-latest
  #   needs: [setup_environment, build_frontend]
  #   steps:
  #     - name: Bundle application with PyInstaller
  #       run: pyinstaller ./onedir.spec -y
