# Lint, test, and build the application.
#
# This workflow runs when a a commit is pushed. It sets up the programming environment
# and runs linting, testing, and build scripts.
name: Push

on: push

jobs:
  run_tests:
    name: Test
    uses: ./.github/workflows/test.yaml
    with:
      runs-on: ubuntu-latest
      create-artifact: false
