# Lint, test, and build the application.
#
# This workflow runs when a a commit is pushed. It sets up the programming environment
# and runs linting, testing, and build scripts. 
name: Push

on: push

jobs:
  lint_frontend:
    name: Lint Frontend
    uses: ./.github/workflows/lint-frontend.yaml
 