name: On New Tag
on:
  push:
    tags: "*"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/test.yaml
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    with:
      runs-on: ${{ matrix.os }}
      create-artifact: true
      test-release: true

  create-release:
    name: Create release ${{ github.ref_name }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          files: artifacts/*.zip
          discussion_category_name: Announcements
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
