name: Setup Frontend

on:
  workflow_call:
    secrets:
        personal_access_token:
          required: false
jobs:
  setup_environment:
    name: Setup Environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install Node.js dependencies
        run: npm install
