name: Test, Lint, and Build

on:
  workflow_call:
    inputs:
      runs-on:
        description: The runner on which to run this script
        required: true
        type: string
      create-artifact:
        description: True to allow the workflow to create a build artifact
        required: false
        default: false
        type: boolean
      test-release:
        description: True to ensure that release testing is performed
        required: false
        default: false
        type: boolean
    secrets:
      personal_access_token:
        required: false

jobs:
  setup_frontend:
    name: Setup Frontend
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: npm ci
      - uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ inputs.runs-on }}-node_modules
  lint_frontend:
    name: Lint Frontend
    needs: setup_frontend
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: npm ci
      - run: npm run lint
  test_frontend:
    name: Test Frontend
    needs: setup_frontend
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: npm ci
      - run: npm run test-storybook
  build_frontend:
    name: Build Frontend
    needs: setup_frontend
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: npm ci
      - run: npm run build
      - uses: actions/cache@v5
        with:
          path: www
          key: ${{ inputs.runs-on }}-www

  lint_backend:
    name: Lint Backend
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
          enable-cache: true
      - run: uv sync
      - run: ruff check
      - run: ty check
  test_backend:
    name: Test Backend
    needs: build_frontend
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
          enable-cache: true
      - run: uv sync
      - uses: actions/cache@v5
        with:
          path: www
          key: ${{ inputs.runs-on }}-www
          fail-on-cache-miss: true
      - run: pytest backend/tests --tag-name ${{ github.ref_name }}
        if: ${{ inputs.test-release }}
      - run: pytest
        if: ${{ !inputs.test-release }}
  build_backend:
    name: Build backend
    needs: build_frontend
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
          enable-cache: true
      - run: uv sync
      - uses: actions/cache@v5
        with:
          path: www
          key: ${{ inputs.runs-on }}-www
          fail-on-cache-miss: true
      - uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml
      - run: pyinstaller onedir.spec
      - run: rm -rf "dist/NSO Bridge"
        if: ${{ inputs.runs-on == 'macos-latest' }}
      - uses: actions/upload-artifact@v4
        if: ${{ inputs.create-artifact }}
        with:
          name: nsobridge-${{ runner.os }}
          path: dist
