name: Create runnable
on: [push]
jobs:
  Compile-Executable:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Install Node.js dependencies
        run: npm install
      - name: Build frontend
        run: npm run build

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: "true"
      - name: Setup the virtual environment
        run: uv venv | uv sync
      - name: Compile the application
        run: pyinstaller ${{ github.workspace }}/onedir.spec -y

      - name: Upload the file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: nsobridge-${{ runner.os }}
          path: "./dist/NSO Bridge"
          retention-days: 5 # Optional: how long to keep the artifact
